export const dictionaries = {
  en: {
    nav: { appName: "XQL Academy", tagline: "Learn · Streak · Win", login: "LOG IN", signup: "SIGN UP" },
    hero: { title1: "Learn anything.", title2: "Level up daily.", selectLanguage: "I want to learn..." },
    kids: { tag: "For Kids", badge: "Playful progress", title: "Interactive world of topics", desc: "A mix of everything children love to explore...", artTitle: "Stories, sounds, rewards, and bright little wins in one happy space.", artDesc: "A dedicated kids view that feels safe, colorful, and exciting from the first tap.", stat1Title: "5 min", stat1Desc: "bite-size play sessions", stat2Title: "Daily", stat2Desc: "streak stars and rewards", stat3Title: "Speak", stat3Desc: "listen, repeat, and smile" },
    students: { tag: "For Students", badge: "Focused momentum", artTitle: "Study spaces that feel active, modern, and built for visible progress.", artDesc: "A sharper student experience with smart visuals, revision energy, and animated feedback that keeps learning moving.", stat1Title: "12", stat1Desc: "subject tracks with guided practice", stat2Title: "Quick", stat2Desc: "revision loops before exams", stat3Title: "Live", stat3Desc: "progress bars, goals, and streaks", title: "Ace your school subjects", desc: "Structured lessons for Class 1-12. Master every subject with quizzes, explanations, progress tracking, and revision flows that feel motivating instead of heavy.", pill1: "Exam-ready drills", pill2: "Animated progress", pill3: "Fast revision wins" },
    exams: { tag: "Higher Level & Competitive Exams", title: "Crack the toughest exams", desc: "Focused prep for India's most competitive exams with structured paths, mock tests, revision cycles, and expert content that feels high-energy and goal driven.", stat1Title: "12 Tracks", stat1Desc: "UPSC to CA paths", stat2Title: "Timed Mocks", stat2Desc: "real pressure practice", stat3Title: "Rank Lifts", stat3Desc: "clear performance feedback", pill1: "Daily Mock Tests", pill2: "Rank Prediction", pill3: "Syllabus Trackers" }
  },
  es: {
    nav: { appName: "Academia XQL", tagline: "Aprende · Racha · Gana", login: "INICIAR SESIÓN", signup: "REGISTRARSE" },
    hero: { title1: "Aprende cualquier cosa.", title2: "Sube de nivel a diario.", selectLanguage: "Quiero aprender..." },
    kids: { tag: "Para Niños", badge: "Progreso lúdico", title: "Mundo interactivo de temas", desc: "Una mezcla de todo lo que a los niños les encanta explorar...", artTitle: "Historias, sonidos, recompensas y pequeñas victorias en un lugar feliz.", artDesc: "Una vista dedicada a los niños que se siente segura y colorida.", stat1Title: "5 min", stat1Desc: "sesiones de juego breves", stat2Title: "Diario", stat2Desc: "estrellas de racha y premios", stat3Title: "Habla", stat3Desc: "escucha, repite y sonríe" },
    students: { tag: "Para Estudiantes", badge: "Impulso centrado", artTitle: "Espacios de estudio activos y modernos.", artDesc: "Una experiencia más aguda con visuales inteligentes y retroalimentación animada.", stat1Title: "12", stat1Desc: "materias con práctica", stat2Title: "Rápido", stat2Desc: "bucles de revisión", stat3Title: "En vivo", stat3Desc: "barras de progreso y rachas", title: "Domina tus materias", desc: "Lecciones estructuradas para las Clases 1-12. Domina cada materia con cuestionarios.", pill1: "Ejercicios listos", pill2: "Progreso animado", pill3: "Revisiones rápidas" },
    exams: { tag: "Exámenes Competitivos", title: "Supera los exámenes más difíciles", desc: "Preparación enfocada para exámenes competitivos con rutas estructuradas.", stat1Title: "12 Rutas", stat1Desc: "Múltiples caminos", stat2Title: "Simulacros", stat2Desc: "práctica bajo presión", stat3Title: "Rankings", stat3Desc: "retroalimentación clara", pill1: "Pruebas diarias", pill2: "Predicción de ranking", pill3: "Rastreadores" }
  },
  fr: {
    nav: { appName: "Académie XQL", tagline: "Apprendre · Série · Gagner", login: "CONNEXION", signup: "S'INSCRIRE" },
    hero: { title1: "Apprenez tout.", title2: "Progressez chaque jour.", selectLanguage: "Je veux apprendre..." },
    kids: { tag: "Pour les Enfants", badge: "Progrès ludique", title: "Monde interactif de sujets", desc: "Un mélange de tout ce que les enfants aiment...", artTitle: "Histoires, sons et récompenses dans un espace joyeux.", artDesc: "Une vue dédiée qui est sûre, colorée et passionnante.", stat1Title: "5 min", stat1Desc: "sessions de jeu courtes", stat2Title: "Quotidien", stat2Desc: "étoiles et récompenses", stat3Title: "Parle", stat3Desc: "écoute, répète et souris" },
    students: { tag: "Pour les Étudiants", badge: "Élan concentré", artTitle: "Des espaces d'étude actifs et modernes.", artDesc: "Une expérience plus fine avec des visuels intelligents.", stat1Title: "12", stat1Desc: "pistes de sujets", stat2Title: "Rapide", stat2Desc: "boucles de révision", stat3Title: "En Direct", stat3Desc: "barres de progression", title: "Maîtrisez vos matières", desc: "Leçons structurées pour les classes 1-12. Maîtrisez chaque sujet avec des quiz.", pill1: "Exercices d'examen", pill2: "Progrès animés", pill3: "Révisions rapides" },
    exams: { tag: "Examens Compétitifs", title: "Réussissez les examens", desc: "Préparation ciblée pour des examens compétitifs avec des chemins structurés.", stat1Title: "12 Pistes", stat1Desc: "cheminements multiples", stat2Title: "Simulations", stat2Desc: "pratique sous pression", stat3Title: "Classements", stat3Desc: "retours de performance", pill1: "Tests quotidiens", pill2: "Prédiction de rang", pill3: "Suivis de programme" }
  },
  de: {
    nav: { appName: "XQL Akademie", tagline: "Lernen · Serie · Gewinnen", login: "ANMELDEN", signup: "REGISTRIEREN" },
    hero: { title1: "Lerne alles.", title2: "Steige täglich auf.", selectLanguage: "Ich möchte lernen..." },
    kids: { tag: "Für Kinder", badge: "Spielerischer Fortschritt", title: "Interaktive Themenwelt", desc: "Eine Mischung aus allem, was Kinder gerne entdecken...", artTitle: "Geschichten, Geräusche und Belohnungen an einem fröhlichen Ort.", artDesc: "Ein eigener Bereich, der sicher, bunt und spannend ist.", stat1Title: "5 Min", stat1Desc: "kurze Spielsitzungen", stat2Title: "Täglich", stat2Desc: "Stern-Serien und Belohnungen", stat3Title: "Sprechen", stat3Desc: "zuhören, wiederholen und lächeln" },
    students: { tag: "Für Studenten", badge: "Fokussierter Schwung", artTitle: "Lernräume, die sich aktiv und modern anfühlen.", artDesc: "Eine schärfere Lernerfahrung mit intelligenten Grafiken.", stat1Title: "12", stat1Desc: "Themenbereiche mit geführter Praxis", stat2Title: "Schnell", stat2Desc: "Wiederholungsschleifen", stat3Title: "Live", stat3Desc: "Fortschrittsbalken und Ziele", title: "Meistere deine Schulfächer", desc: "Strukturierte Lektionen für die Klassen 1-12. Meistere jedes Fach durch Quizze.", pill1: "Prüfungsübungen", pill2: "Animierter Fortschritt", pill3: "Schnelle Wiederholung" },
    exams: { tag: "Leistungstests", title: "Knacke die härtesten Prüfungen", desc: "Fokussierte Vorbereitung auf wettbewerbsfähige Prüfungen mit strukturierten Wegen.", stat1Title: "12 Pfade", stat1Desc: "verschiedene Kurse", stat2Title: "Prüfungen", stat2Desc: "Üben unter Druck", stat3Title: "Ränge", stat3Desc: "klares Leistungsfeedback", pill1: "Tägliche Tests", pill2: "Rangvorhersage", pill3: "Lehrplantracker" }
  },
  ja: {
    nav: { appName: "XQLアカデミー", tagline: "学ぶ · 継続 · 勝つ", login: "ログイン", signup: "登録" },
    hero: { title1: "何でも学ぼう", title2: "毎日レベルアップ。", selectLanguage: "学びたい言語..." },
    kids: { tag: "子供向け", badge: "遊びながら進歩", title: "インタラクティブなトピック", desc: "子供たちが探求するのが好きなものすべて...", artTitle: "物語、音声、報酬、そして小さな勝利。", artDesc: "安全でカラフルな専用の子供向けビュー。", stat1Title: "5分", stat1Desc: "短時間のプレイ", stat2Title: "毎日", stat2Desc: "継続の星と報酬", stat3Title: "話す", stat3Desc: "聞いて、繰り返して、笑う" },
    students: { tag: "学生向け", badge: "集中した勢い", artTitle: "アクティブでモダンな学習スペース。", artDesc: "アニメーション化されたフィードバックによるシャープな学生体験。", stat1Title: "12", stat1Desc: "ガイド付きの科目", stat2Title: "迅速", stat2Desc: "復習ループ", stat3Title: "ライブ", stat3Desc: "進行状況バーと目標", title: "学校の科目をマスター", desc: "グレード1〜12向けの構造化されたレッスン。 クイズと説明で習得。", pill1: "試験対策", pill2: "アニメーションの進行", pill3: "高速復習" },
    exams: { tag: "競争試験", title: "最も難しい試験を突破", desc: "構造化されたパスや模擬テストでの競争試験の準備。", stat1Title: "12コース", stat1Desc: "複数のパス", stat2Title: "模擬テスト", stat2Desc: "プレッシャーの中の練習", stat3Title: "ランク付け", stat3Desc: "明確なフィードバック", pill1: "毎日のテスト", pill2: "ランク予測", pill3: "シラバストラッカー" }
  },
  ko: {
    nav: { appName: "XQL 아카데미", tagline: "학습 · 연속 · 승리", login: "로그인", signup: "가입하기" },
    hero: { title1: "무엇이든 배우세요.", title2: "매일 레벨업.", selectLanguage: "제가 배우고 싶은 것은..." },
    kids: { tag: "어린이용", badge: "즐거운 진행", title: "인터랙티브 주제 세계", desc: "아이들이 좋아하는 모든 것...", artTitle: "이야기, 소리, 보상을 한곳에서.", artDesc: "안전하고 컬러풀하며 흥미진진한 전용 보기.", stat1Title: "5분", stat1Desc: "짧은 플레이 세션", stat2Title: "매일", stat2Desc: "연속 보상", stat3Title: "말하기", stat3Desc: "듣고 따라하며 웃기" },
    students: { tag: "학생용", badge: "집중된 추진력", artTitle: "눈에 띄는 발전을 위한 학습 공간.", artDesc: "스마트한 시각 및 피드백.", stat1Title: "12", stat1Desc: "가이드 제공 과목", stat2Title: "빠른", stat2Desc: "복습 루프", stat3Title: "라이브", stat3Desc: "진행 표시줄", title: "학교 과목 마스터하기", desc: "1-12학년을 위한 체계적인 수업. 퀴즈로 과목을 마스터하세요.", pill1: "시험 대비", pill2: "애니메이션 진행", pill3: "빠른 복습" },
    exams: { tag: "경쟁 시험", title: "가장 어려운 시험 돌파", desc: "체계적인 경로를 제공하는 경쟁 시험 준비.", stat1Title: "12 경로", stat1Desc: "다양한 교육 과정", stat2Title: "모의고사", stat2Desc: "실전 연습", stat3Title: "순위 상승", stat3Desc: "명확한 피드백", pill1: "일일 테스트", pill2: "순위 예측", pill3: "학습 진행기" }
  },
  hi: {
    nav: { appName: "एक्सक्यूएल अकादमी", tagline: "सीखें · स्ट्रीक · जीतें", login: "लॉग इन", signup: "साइन अप" },
    hero: { title1: "कुछ भी सीखें।", title2: "रोजाना आगे बढ़ें।", selectLanguage: "मैं सीखना चाहता हूँ..." },
    kids: { tag: "बच्चों के लिए", badge: "खेल-खेल में प्रगति", title: "विषयों की इंटरैक्टिव दुनिया", desc: "वह सब कुछ जो बच्चों को पसंद है...", artTitle: "कहानियां, ध्वनियां, इनाम और एक खुशहाल जगह में जीतें।", artDesc: "एक समर्पित किड्स व्यू जो सुरक्षित और रंगीन लगता है।", stat1Title: "5 मिनट", stat1Desc: "छोटे-छोटे खेलने के सत्र", stat2Title: "रोजाना", stat2Desc: "स्ट्रीक स्टार्स और इनाम", stat3Title: "बोलें", stat3Desc: "सुनें, दोहराएं और मुस्कुराएं" },
    students: { tag: "छात्रों के लिए", badge: "केंद्रित गति", artTitle: "अध्ययन स्थान जो सक्रिय और प्रगति के लिए बनाए गए हैं।", artDesc: "स्मार्ट विज़ुअल्स के साथ एक तेज छात्र अनुभव।", stat1Title: "12", stat1Desc: "निर्देशित अभ्यास के साथ विषय", stat2Title: "त्वरित", stat2Desc: "रिवीजन लूप", stat3Title: "लाइव", stat3Desc: "प्रगति और लक्ष्य", title: "स्कूल के विषयों में अव्वल आएं", desc: "कक्षा 1-12 के लिए संरचित पाठ्यक्रम।", pill1: "परीक्षा अभ्यास", pill2: "एनिमेटेड प्रगति", pill3: "तेज रिवीजन" },
    exams: { tag: "प्रतियोगी परीक्षाएँ", title: "सबसे कठिन परीक्षाएँ पास करें", desc: "भारत की प्रतियोगी परीक्षाओं की तैयारी।", stat1Title: "12 ट्रैक", stat1Desc: "विविध पथ", stat2Title: "समयबद्ध मॉक", stat2Desc: "दबाव में अभ्यास", stat3Title: "रैंक बढ़ाएँ", stat3Desc: "स्पष्ट प्रतिक्रिया", pill1: "दैनिक मॉक", pill2: "रैंक भविष्यवाणी", pill3: "पाठ्यक्रम ट्रैकर्स" }
  },
  zh: {
    nav: { appName: "XQL学院", tagline: "学习 · 坚持 · 成功", login: "登录", signup: "注册" },
    hero: { title1: "学习任何东西。", title2: "每天提升。", selectLanguage: "我想学习..." },
    kids: { tag: "儿童", badge: "快乐的进步", title: "互动的世界", desc: "孩子们喜欢探索的一切...", artTitle: "故事、声音和奖励都在一个快乐的地方。", artDesc: "安全、色彩缤纷且激动人心的儿童专区。", stat1Title: "5分钟", stat1Desc: "游戏化学习", stat2Title: "每天", stat2Desc: "打卡星星", stat3Title: "口语", stat3Desc: "听、重复、笑" },
    students: { tag: "学生", badge: "专注的学习", artTitle: "现代且活跃的学习空间。", artDesc: "智能视觉和动画反馈让你不断前进。", stat1Title: "12", stat1Desc: "有指导的科目", stat2Title: "快速", stat2Desc: "复习循环", stat3Title: "实时", stat3Desc: "进度条和目标", title: "掌握学校科目", desc: "适合1-12年级的系统化课程。通过测验和讲解掌握每一门科目。", pill1: "考试演练", pill2: "动画进度", pill3: "快速复习" },
    exams: { tag: "竞争性考试", title: "攻克最难的考试", desc: "通过系统的真题和测验，专注于最硬核的考试准备。", stat1Title: "12 条路径", stat1Desc: "多种追踪", stat2Title: "模考", stat2Desc: "实战演练", stat3Title: "排名提升", stat3Desc: "清晰的绩效反馈", pill1: "每日测验", pill2: "排名预测", pill3: "教学大纲追踪" }
  },
  it: {
    nav: { appName: "Accademia XQL", tagline: "Impara · Serie · Vinci", login: "ACCEDI", signup: "ISCRIVITI" },
    hero: { title1: "Impara di tutto.", title2: "Sali di livello ogni giorno.", selectLanguage: "Voglio imparare..." },
    kids: { tag: "Per Bambini", badge: "Progresso giocoso", title: "Mondo interattivo", desc: "Un mix di tutto ciò che i bambini amano...", artTitle: "Storie, suoni e ricompense in uno spazio felice.", artDesc: "Una vista per bambini dedicata, sicura e colorata.", stat1Title: "5 min", stat1Desc: "gioco breve", stat2Title: "Quotidiano", stat2Desc: "stelle e premi", stat3Title: "Parla", stat3Desc: "ascolta, ripeti e sorridi" },
    students: { tag: "Per Studenti", badge: "Slancio concentrato", artTitle: "Spazi di studio attivi e moderni.", artDesc: "Un'esperienza studentesca con elementi visivi intelligenti.", stat1Title: "12", stat1Desc: "materie guidate", stat2Title: "Veloce", stat2Desc: "cicli di revisione", stat3Title: "Live", stat3Desc: "barre di avanzamento", title: "Supera le tue materie", desc: "Lezioni strutturate per le classi 1-12. Padroneggia ogni materia con i quiz.", pill1: "Esercizi d'esame", pill2: "Progresso animato", pill3: "Revisione veloce" },
    exams: { tag: "Esami Competitivi", title: "Supera gli esami più duri", desc: "Preparazione mirata per gli esami competitivi con percorsi strutturati.", stat1Title: "12 Percorsi", stat1Desc: "vari percorsi", stat2Title: "Simulazioni", stat2Desc: "pratica sotto pressione", stat3Title: "Classifiche", stat3Desc: "feedback chiaro", pill1: "Test quotidiani", pill2: "Previsione rango", pill3: "Tracciamento programma" }
  },
  pt: {
    nav: { appName: "Academia XQL", tagline: "Aprenda · Sequência · Ganhe", login: "ENTRAR", signup: "INSCREVER-SE" },
    hero: { title1: "Aprenda qualquer coisa.", title2: "Suba de nível diariamente.", selectLanguage: "Eu quero aprender..." },
    kids: { tag: "Para Crianças", badge: "Progresso lúdico", title: "Mundo interativo", desc: "Uma mistura de tudo que as crianças adoram explora...", artTitle: "Histórias, sons e recompensas em um lugar feliz.", artDesc: "Uma visão dedicada e segura.", stat1Title: "5 min", stat1Desc: "sessões de jogo", stat2Title: "Diariamente", stat2Desc: "estrelas de racha", stat3Title: "Fale", stat3Desc: "ouça e repita" },
    students: { tag: "Para Estudantes", badge: "Foco total", artTitle: "Espaços ativos e modernos.", artDesc: "Uma experiência com visuais inteligentes.", stat1Title: "12", stat1Desc: "matérias com guias", stat2Title: "Rápido", stat2Desc: "ciclos de revisão", stat3Title: "Ao Vivo", stat3Desc: "barras de progresso", title: "Domine suas disciplinas", desc: "Aulas estruturadas. Domine cada assunto.", pill1: "Prática p/ Exames", pill2: "Progresso Animado", pill3: "Revisão Rápida" },
    exams: { tag: "Exames Competitivos", title: "Passe nos piores exames", desc: "Preparação focada e simulados.", stat1Title: "12 Trilhas", stat1Desc: "caminhos", stat2Title: "Simulados", stat2Desc: "pressão", stat3Title: "Ranking", stat3Desc: "feedback forte", pill1: "Testes Diários", pill2: "Previsão", pill3: "Rastreio" }
  },
  ru: {
    nav: { appName: "Академия XQL", tagline: "Учись · Серия · Побеждай", login: "ВОЙТИ", signup: "РЕГИСТРАЦИЯ" },
    hero: { title1: "Изучай всё что угодно.", title2: "Повышай уровень каждый день.", selectLanguage: "Я хочу изучать..." },
    kids: { tag: "Для Детей", badge: "Игровой прогресс", title: "Интерактивный мир", desc: "Смесь всего, что любят дети...", artTitle: "Истории, звуки и награды в одном счастливом месте.", artDesc: "Безопасное и красочное пространство.", stat1Title: "5 мин", stat1Desc: "короткие сессии", stat2Title: "Ежедневно", stat2Desc: "звезды серии", stat3Title: "Говори", stat3Desc: "слушай и повторяй" },
    students: { tag: "Для Студентов", badge: "Сфокусированный импульс", artTitle: "Активные и современные учебные пространства.", artDesc: "Четкий опыт с умной визуализацией.", stat1Title: "12", stat1Desc: "предметов с руководством", stat2Title: "Быстро", stat2Desc: "циклы повторения", stat3Title: "В реальном времени", stat3Desc: "прогресс-бары", title: "Улучши оценки", desc: "Структурированные уроки для 1-12 классов.", pill1: "Экзаменационные тесты", pill2: "Живой прогресс", pill3: "Быстрое повторение" },
    exams: { tag: "Сложные экзамены", title: "Сдай самые трудные тесты", desc: "Подготовка к сложнейшим экзаменам с тестами.", stat1Title: "12 Путей", stat1Desc: "разные курсы", stat2Title: "Тесты", stat2Desc: "практика под давлением", stat3Title: "Рейтинги", stat3Desc: "четкая обратная связь", pill1: "Ежедневные тесты", pill2: "Прогноз рейтинга", pill3: "Прогресс по темам" }
  },
  ar: {
    nav: { appName: "أكاديمية XQL", tagline: "تعلم · استمر · اربح", login: "دخول", signup: "تسجيل" },
    hero: { title1: "تعلم أي شيء.", title2: "ارتقِ بمستواك يوميًا.", selectLanguage: "أريد أن أتعلم..." },
    kids: { tag: "للأطفال", badge: "لعب وتقدم", title: "عالم تفاعلي", desc: "مزيج من كل ما يحبه الأطفال...", artTitle: "قصص وأصوات ومكافآت.", artDesc: "بيئة آمنة وملونة وممتعة.", stat1Title: "5 دقائق", stat1Desc: "لعب سريع", stat2Title: "يومياً", stat2Desc: "نجوم استمرارية", stat3Title: "تحدث", stat3Desc: "استمع وكرر" },
    students: { tag: "للطلاب", badge: "تركيز مضاعف", artTitle: "مساحات دراسية نشطة.", artDesc: "تجربة بصرية ممتعة للطلاب.", stat1Title: "12", stat1Desc: "مواد وتوجيه", stat2Title: "سريع", stat2Desc: "مراجعة الامتحان", stat3Title: "مباشر", stat3Desc: "أهداف ومسار", title: "تفوق في دراستك", desc: "دروس منظمة للطلاب للتميز بالمدارس.", pill1: "تدريب امتحان", pill2: "تقدم ملحوظ", pill3: "مراجعة سهلة" },
    exams: { tag: "الامتحانات التنافسية", title: "اجتز أصعب الاختبارات", desc: "إعداد ذكي وتدريب مكثف.", stat1Title: "12 مسار", stat1Desc: "مسارات تدريب", stat2Title: "تجارب", stat2Desc: "تدريب عملي", stat3Title: "ترتيب", stat3Desc: "متابعة أداء", pill1: "تجارب يومية", pill2: "توقع الترتيب", pill3: "متابعة المنهج" }
  },
  mr: {
    nav: { appName: "XQL अकॅडमी", tagline: "शिका · स्ट्रिक · जिंका", login: "लॉग इन", signup: "साइन अप" },
    hero: { title1: "काहीही शिका.", title2: "दररोज पातळी वाढवा.", selectLanguage: "मला शिकायचे आहे..." },
    kids: { tag: "मुलांसाठी", badge: "खेळकर प्रगती", title: "परस्परसंवादी जग", desc: "मुलांना आवडेल असे सर्वकाही...", artTitle: "गोष्टी, आवाज आणि बक्षिसे एकाच आनंदी जागेत.", artDesc: "सुरक्षित आणि रंगीत जागा.", stat1Title: "5 मिनिटे", stat1Desc: "लहान खेळ सत्र", stat2Title: "दररोज", stat2Desc: "स्ट्रिक स्टार्स", stat3Title: "बोला", stat3Desc: "ऐका आणि पुन्हा करा" },
    students: { tag: "विद्यार्थ्यांसाठी", badge: "लक्ष्य केंद्रित", artTitle: "सक्रिय आणि आधुनिक अभ्यासाची ठिकाणे.", artDesc: "स्मार्ट व्हिज्युअल्स आणि फीडबॅक.", stat1Title: "12", stat1Desc: "मार्गदर्शित विषय", stat2Title: "जलद", stat2Desc: "परीक्षेपूर्वी रिव्हिजन", stat3Title: "थेट", stat3Desc: "प्रगती आणि ध्येये", title: "शाळेच्या विषयात अव्वल राहा", desc: "इयत्ता 1-12 साठी अभ्यासक्रम.", pill1: "परीक्षा सराव", pill2: "प्रगती ट्रॅकिंग", pill3: "जलद रिव्हिजन" },
    exams: { tag: "स्पर्धा परीक्षा", title: "सर्वात कठीण परीक्षा पास करा", desc: "भारतातील स्पर्धा परीक्षांची तयारी.", stat1Title: "12 मार्ग", stat1Desc: "मार्गदर्शन", stat2Title: "मॉक टेस्ट", stat2Desc: "प्रत्यक्ष सराव", stat3Title: "रँक वाढ", stat3Desc: "स्पष्ट फीडबॅक", pill1: "दैनिक मॉक", pill2: "रँक अंदाज", pill3: "अभ्यासक्रम ट्रॅकर" }
  },
  ta: {
    nav: { appName: "XQL அகாடமி", tagline: "கற்று · தொடர் · வெல்", login: "உள்நுழைக", signup: "பதிவு செய்க" },
    hero: { title1: "எதையும் கற்றுக்கொள்ளுங்கள்.", title2: "தினமும் முன்னெறுங்கள்.", selectLanguage: "நான் கற்க விரும்புவது..." },
    kids: { tag: "குழந்தைகளுக்காக", badge: "விளையாட்டான முன்னேற்றம்", title: "இண்டராக்டிவ் உலகம்", desc: "குழந்தைகள் விரும்பும் அனைத்தும்...", artTitle: "கதைகள், ஒலிகள் மற்றும் பரிசுகள்.", artDesc: "பாதுகாப்பான இட அமைப்பு.", stat1Title: "5 நிமிடம்", stat1Desc: "சிறிய விளையாட்டு", stat2Title: "தினசரி", stat2Desc: "பரிசுகள்", stat3Title: "பேசுங்கள்", stat3Desc: "கேட்டு திரும்ப சொல்லவும்" },
    students: { tag: "மாணவர்களுக்காக", badge: "கவனமான முன்னேற்றம்", artTitle: "சுறுசுறுப்பான படிப்பு இடங்கள்.", artDesc: "தெளிவான மாணவர் அனுபவம்.", stat1Title: "12", stat1Desc: "பாடங்கள்", stat2Title: "விரைவில்", stat2Desc: "திருப்புதல்", stat3Title: "நேரடி", stat3Desc: "இலக்குகள்", title: "பள்ளி பாடங்களை கற்று தேருங்கள்", desc: "வகுப்பு 1-12 பாடங்கள்.", pill1: "தேர்வு பயிற்சி", pill2: "முன்னேற்றம்", pill3: "விரைவான திருப்புதல்" },
    exams: { tag: "போட்டித் தேர்வுகள்", title: "கடினமான தேர்வுகளை வெல்லுங்கள்", desc: "போட்டித் தேர்வுக்கான சிறந்த பயிற்சி.", stat1Title: "12 பாதைகள்", stat1Desc: "பல்வேறு பாடங்கள்", stat2Title: "மாதிரி தேர்வு", stat2Desc: "பயிற்சிகள்", stat3Title: "ரேங்க்", stat3Desc: "வளர்ச்சி அறிக்கை", pill1: "தினசரி டெஸ்ட்", pill2: "ரேங்க் கணிப்பு", pill3: "பாடத்திட்டங்கள்" }
  },
  te: {
    nav: { appName: "XQL అకాడమీ", tagline: "నేర్చుకో · స్ట్రీక్ · గెలువు", login: "లాగిన్", signup: "సైన్ అప్" },
    hero: { title1: "ఏదైనా నేర్చుకోండి.", title2: "రోజూ ఎదగండి.", selectLanguage: "నేను నేర్చుకోవాలనుకుంటున్నాను..." },
    kids: { tag: "పిల్లల కోసం", badge: "ఆటల పురోగతి", title: "ఇంటరాక్టివ్ ప్రపంచం", desc: "పిల్లలు ఇష్టపడేవన్నీ...", artTitle: "కథలు, శబ్దాలు, బహుమతులు.", artDesc: "సురక్షితమైన మరియు రంగుల ప్రపంచం.", stat1Title: "5 నిమిషాలు", stat1Desc: "చిన్న ఆటలు", stat2Title: "రోజూ", stat2Desc: "స్ట్రీక్ బహుమతులు", stat3Title: "మాట్లాడు", stat3Desc: "విను మరియు చెప్పండి" },
    students: { tag: "విద్యార్థుల కోసం", badge: "ఏకాగ్రత", artTitle: "క్రియాశీలమైన అధ్యయన ప్రదేశాలు.", artDesc: "స్మార్ట్ విజువల్స్‌తో అనుభవం.", stat1Title: "12", stat1Desc: "సబ్జెక్టులు", stat2Title: "తొరగా", stat2Desc: "పరీక్షల ముందు పునర్విమర్శ", stat3Title: "లైవ్", stat3Desc: "పురోగతి బార్‌లు", title: "మీ సబ్జెక్టులలో ఏస్ అవ్వండి", desc: "క్లాస్ 1-12 కోసం పాఠాలు.", pill1: "పరీక్ష శిక్షణ", pill2: "పురోగతి", pill3: "వేగవంతమైన మదింపు" },
    exams: { tag: "పోటీ పరీక్షలు", title: "కష్టమైన పరీక్షలు పగులగొట్టండి", desc: "పోటీ పరీక్షల తయారీ.", stat1Title: "12 మార్గాలు", stat1Desc: "గైడెన్స్", stat2Title: "మాక్ టెస్ట్స్", stat2Desc: "సాధన", stat3Title: "ర్యాంక్", stat3Desc: "ఫీడ్‌బ్యాక్", pill1: "రోజువారీ పరీక్షలు", pill2: "ర్యాంక్ అంచనా", pill3: "సిలబస్ ట్రాకింగ్" }
  },
  bn: {
    nav: { appName: "XQL একাডেমি", tagline: "শিখুন · স্ট্রিক · জিতুন", login: "লগ ইন", signup: "সাইন আপ" },
    hero: { title1: "যেকোনো কিছু শিখুন।", title2: "প্রতিদিন এগিয়ে যান।", selectLanguage: "আমি শিখতে চাই..." },
    kids: { tag: "বাচ্চাদের জন্য", badge: "খেলার ছলে অগ্রগতি", title: "ইন্টারেক্টিভ বিশ্ব", desc: "বাচ্চাদের পছন্দের সবকিছু...", artTitle: "গল্প, শব্দ এবং পুরষ্কার একটি আনন্দময় স্থানে।", artDesc: "নিরাপদ এবং রঙিন স্থান।", stat1Title: "৫ মিনিট", stat1Desc: "ছোট খেলার সেশন", stat2Title: "রোজ", stat2Desc: "পুরষ্কার", stat3Title: "বলুন", stat3Desc: "শুনুন, পুনরাবৃত্তি করুন" },
    students: { tag: "শিক্ষার্থীদের জন্য", badge: "কেন্দ্রিক গতি", artTitle: "সক্রিয় এবং আধুনিক অধ্যয়নের স্থান।", artDesc: "ছাত্রদের স্মার্ট অভিজ্ঞতা।", stat1Title: "১২", stat1Desc: "বিষয় ট্র্যাক", stat2Title: "দ্রুত", stat2Desc: "রিভিশন", stat3Title: "লাইভ", stat3Desc: "অগ্রগতি এবং লক্ষ্য", title: "স্কুলের বিষয়ে শীর্ষে থাকুন", desc: "১-১২ শ্রেণীর পাঠ্যক্রম।", pill1: "পরীক্ষার প্রস্তুতি", pill2: "অগ্রগতি", pill3: "দ্রুত রিভিশন" },
    exams: { tag: "প্রতিযোগিতামূলক পরীক্ষা", title: "কঠিন পরীক্ষায় উত্তীর্ণ হোন", desc: "কঠিন পরীক্ষার প্রস্তুতি।", stat1Title: "১২ টি পথ", stat1Desc: "বিভিন্ন কোর্স", stat2Title: "মক টেস্ট", stat2Desc: "চাপের মধ্যে অনুশীলন", stat3Title: "র‍্যাঙ্ক", stat3Desc: "সাফল্যের প্রতিক্রিয়া", pill1: "দৈনিক মক", pill2: "র‍্যাঙ্ক পূর্বাভাস", pill3: "সিলেবাস ট্র্যাকার" }
  },
  id: {
    nav: { appName: "Akademi XQL", tagline: "Belajar · Streak · Menang", login: "MASUK", signup: "DAFTAR" },
    hero: { title1: "Pelajari apa saja.", title2: "Naik level setiap hari.", selectLanguage: "Saya ingin belajar..." },
    kids: { tag: "Untuk Anak", badge: "Kemajuan bermain", title: "Dunia interaktif", desc: "Campuran hal yang disukai anak...", artTitle: "Cerita, suara, dan hadiah di satu tempat.", artDesc: "Aman dan penuh warna.", stat1Title: "5 mnt", stat1Desc: "sesi bermain singkat", stat2Title: "Harian", stat2Desc: "hadiah streak", stat3Title: "Bicara", stat3Desc: "dengar dan ulangi" },
    students: { tag: "Untuk Pelajar", badge: "Fokus maksimum", artTitle: "Ruang belajar modern dan aktif.", artDesc: "Pengalaman belajar siswa yang tajam.", stat1Title: "12", stat1Desc: "pelajaran terpandu", stat2Title: "Cepat", stat2Desc: "sesi revisi", stat3Title: "Live", stat3Desc: "progres dan tujuan", title: "Kuasai pelajaran", desc: "Pelajaran kelas 1-12 yang terstruktur.", pill1: "Latihan Ujian", pill2: "Progres Nyata", pill3: "Revisi Cepat" },
    exams: { tag: "Ujian Kompetitif", title: "Lulus ujian tersulit", desc: "Persiapan matang ujian kompetitif.", stat1Title: "12 Jalur", stat1Desc: "banyak pilihan", stat2Title: "Tes Simulasi", stat2Desc: "latihan langsung", stat3Title: "Peringkat", stat3Desc: "umpan balik cepat", pill1: "Tes Harian", pill2: "Prediksi Peringkat", pill3: "Pelacak Silabus" }
  },
  tr: {
    nav: { appName: "XQL Akademi", tagline: "Öğren · Seri · Kazan", login: "GİRİŞ", signup: "KAYIT OL" },
    hero: { title1: "Her şeyi öğren.", title2: "Her gün seviye atla.", selectLanguage: "Öğrenmek istiyorum..." },
    kids: { tag: "Çocuklar İçin", badge: "Eğlenceli İlerleme", title: "İnteraktif dünya", desc: "Çocukların sevdiği her şey...", artTitle: "Mutlu bir yerde hikayeler ve ödüller.", artDesc: "Güvenli ve renkli bir alan.", stat1Title: "5 dk", stat1Desc: "kısa oyun", stat2Title: "Günlük", stat2Desc: "seri ve yıldız", stat3Title: "Konuş", stat3Desc: "dinle ve tekrarla" },
    students: { tag: "Öğrenciler İçin", badge: "Odaklanma", artTitle: "Modern çalışma alanları.", artDesc: "Kapsamlı bir öğrenci deneyimi.", stat1Title: "12", stat1Desc: "yönlendirmeli konu", stat2Title: "Hızlı", stat2Desc: "tekrar döngüsü", stat3Title: "Canlı", stat3Desc: "ilerleme çubuğu", title: "Dersleri Başar", desc: "1-12. sınıflar için yapılandırılmış dersler.", pill1: "Sınav Egzersizi", pill2: "Canlı İlerleme", pill3: "Hızlı Tekrar" },
    exams: { tag: "Rekabetçi Sınavlar", title: "Zorlu sınavları kazan", desc: "Önemli sınavlara hazırlık.", stat1Title: "12 Yön", stat1Desc: "çeşitli alanlar", stat2Title: "Denemeler", stat2Desc: "baskı altında pratik", stat3Title: "Sıralama", stat3Desc: "hızlı geri bildirim", pill1: "Günlük Deneme", pill2: "Derece Tahmini", pill3: "Müfredat Takibi" }
  },
  nl: {
    nav: { appName: "XQL Academie", tagline: "Leer · Reeks · Win", login: "INLOGGEN", signup: "REGISTREREN" },
    hero: { title1: "Leer van alles.", title2: "Stijg dagelijks in niveau.", selectLanguage: "Ik wil leren..." },
    kids: { tag: "Voor Kinderen", badge: "Speelse vooruitgang", title: "Interactieve wereld", desc: "Dingen die kinderen graag ontdekken...", artTitle: "Verhalen, geluiden en beloningen.", artDesc: "Een veilige en kleurrijke weergave.", stat1Title: "5 min", stat1Desc: "korte speelsessies", stat2Title: "Dagelijks", stat2Desc: "reeks en sterren", stat3Title: "Spreek", stat3Desc: "luister en herhaal" },
    students: { tag: "Voor Studenten", badge: "Grote focus", artTitle: "Actieve en moderne leerruimtes.", artDesc: "Slimme visuals en feedback.", stat1Title: "12", stat1Desc: "geleide vakken", stat2Title: "Snel", stat2Desc: "herhalingssessies", stat3Title: "Live", stat3Desc: "voortgangsbalken", title: "Beheers je schoolvakken", desc: "Structuurlessen voor de hele rit.", pill1: "Examentoetsen", pill2: "Live Voortgang", pill3: "Snelle Herhaling" },
    exams: { tag: "Competitieve Examens", title: "Kraak zware examens", desc: "Examentraining met tests en doelen.", stat1Title: "12 Paden", stat1Desc: "veel cursussen", stat2Title: "Proefexamens", stat2Desc: "oefenen onder druk", stat3Title: "Ranglijst", stat3Desc: "duidelijke feedback", pill1: "Dagelijkse Tests", pill2: "Rangschikking", pill3: "Syllabus Tracker" }
  },
  pl: {
    nav: { appName: "Akademia XQL", tagline: "Ucz się · Seria · Wygrywaj", login: "ZALOGUJ", signup: "REJESTRACJA" },
    hero: { title1: "Ucz się wszystkiego.", title2: "Poziom wyżej każdego dnia.", selectLanguage: "Chcę się uczyć..." },
    kids: { tag: "Dla Dzieci", badge: "Wesoły Postęp", title: "Interaktywny Świat", desc: "Zbiór wszystkiego, co dzieci kochają...", artTitle: "Historie, dźwięki i nagrody.", artDesc: "Bezpieczne i kolorowe miejsce.", stat1Title: "5 min", stat1Desc: "krótkie sesje gry", stat2Title: "Codziennie", stat2Desc: "serie i gwiazdy", stat3Title: "Mów", stat3Desc: "słuchaj i powtarzaj" },
    students: { tag: "Dla Uczniów", badge: "Skoncentrowany Impuls", artTitle: "Aktywne i nowoczesne miejsca nauki.", artDesc: "Ostre wrażenia dla studentów z wizualizacjami.", stat1Title: "12", stat1Desc: "przedmiotów do nauki", stat2Title: "Szybko", stat2Desc: "pętle powtórek", stat3Title: "Na żywo", stat3Desc: "paski postępu", title: "Opanuj przedmioty szkolne", desc: "Uporządkowane lekcje dla klas 1-12.", pill1: "Ćwiczenia do Egzaminu", pill2: "Animowany Postęp", pill3: "Szybka Powtórka" },
    exams: { tag: "Trudne Egzaminy", title: "Zdaj najtrudniejsze egzaminy", desc: "Skoncentrowane przygotowanie do rywalizacji.", stat1Title: "12 Ścieżek", stat1Desc: "wiele dróg do sukcesu", stat2Title: "Próbne testy", stat2Desc: "praktyka pod presją", stat3Title: "Ranking", stat3Desc: "jasna ocena wydajności", pill1: "Codzienne testy", pill2: "Prognoza Oceny", pill3: "Śledzenie Programu" }
  }
};

export type Language = keyof typeof dictionaries;
